### ISSUE TITLE
ruleinput relation type

### ISSUE THREAD

**Issue by mjkoster** [protocol-registries/link-relations#16]
We would like to pre-register the "ruleinput" link relation type. The specification for the use of this type will be available for review later this year.

* Relation Name: 
ruleinput

* Description: 
The resource identified by the link target provides an input value to an instance of a rule, where the resource which represents the rule instance is identified by the link context.

* Reference: 
OCF Core Specification, Open Connectivity Foundation
https://openconnectivity.org/ 
Candidate specification for publication, pending internal review, when available:
https://openconnectivity.org/developer/specifications/draft-specifications

**Comment by mnot** [comment]
We can informally reserve the name, but can't register it until you give us a publicly available reference.

Sorry for not explicitly answering this earlier.

**Comment by mjkoster** [comment]
Yes, this will be OK. The document will be published after OCF member review.

Thanks and best regards,

Michael

**Comment by marktrayer** [comment]
Apologies for the delay in providing this; the value is defined in the following published/public OCF specification: https://openconnectivity.org/specs/OCF_Core_Optional_Specification_v2.2.0.pdf

**Comment by mnot** [comment]
Relation Name: ruleinput

Description: The resource identified by the link target provides an input value to an instance of a rule, where the resource which represents the rule instance is identified by the link context.

Reference: https://openconnectivity.org/specs/OCF_Core_Optional_Specification_v2.2.0.pdf
