### ISSUE TITLE
"manifest" link type

### ISSUE THREAD

**Issue by aarongustafson** [protocol-registries/link-relations#19]
Enter the details of the link relation type below:

* Relation Name: manifest
* Description: Refers to the JSON-based manifest file that provides metadata associated with the current document.
* Reference: https://www.w3.org/TR/appmanifest/

**Comment by aarongustafson** [comment]
Related: w3c/manifest#778

**Comment by mnot** [comment]
The registry already includes `manifest`, with the description "Links to a manifest file for the context." See #14 for background.

Would you like a change to the description? If so, note that the guidance for the registry is that relation types shouldn't specify a media type for what's found at the link.

cc @marcoscaceres

**Comment by marcoscaceres** [comment]
heh, lol.... I'd totally forgot we added this. I think we will want to update the description, and then get it to point to HTML (where the other "Link type X"s are defined).

**Comment by mnot** [comment]
Cool. Can you suggest an updated description and link, taking the above into account?

**Comment by aarongustafson** [comment]
@mnot Let’s go with this.

- description: Refers to the JSON-based manifest file that provides metadata associated with the current document.
- link: https://html.spec.whatwg.org/multipage/links.html#linkTypes

I am working on a PR to the HTML spec for this to be added at the link.

**Comment by mnot** [comment]
Sorry, I should have said -- link relation type descriptions are discouraged from specifying a format, because that's what `type` is for. Also, "provides metadata associated with" is extremely broad, and the preferred technology is "context", not "document", because it's not always a whole document that's the context of the link.

That leaves us with something that looks like the current description; is there additional nuance that you wanted to get in there?

WRT updating the link - we need to get the link actually in the HTML spec before we can do this.

**Comment by marcoscaceres** [comment]
> That leaves us with something that looks like the current description; is there additional nuance that you wanted to get in there?

We shouldn't need anything special here.

> WRT updating the link - we need to get the link actually in the HTML spec before we can do this.

Yeah, we only need this :) We hope to have the link next week. @aarongustafson will prepare a PR for HTML and we will report back once merged.

**Comment by jyasskin** [comment]
I believe the correct link is now https://html.spec.whatwg.org/multipage/links.html#link-type-manifest.

**Comment by marcoscaceres** [comment]
Indeed. Thanks @jyasskin!

**Comment by marcoscaceres** [comment]
@mnot, gentle ping. The conclusion was to retain the current description and just update the link to the HTML spec: 
https://html.spec.whatwg.org/multipage/links.html#link-type-manifest
