### ISSUE TITLE
new "media-feed" type

### ISSUE THREAD

**Issue by beccahughes** [protocol-registries/link-relations#20]
Enter the details of the link relation type below:

* Relation Name: media-feed
* Description: Refers to a feed of personalised media recommendations relevant to the link context
* Reference: https://wicg.github.io/media-feeds/#discovery-of-media-feeds

Any additional information (this will not be included in the registry)?

**Comment by mnot** [comment]
Hi,

It would be great if you could restate the description in terms of how the context relates to the target URI -- e.g., "Refers to a feed of personalised media recommendations relevant to the link context."

**Comment by beccahughes** [comment]
Sure, done

**Comment by mnot** [comment]
Registration request made to IANA. It's not mandatory, but it might be helpful if you added this to <https://wicg.github.io/media-feeds/#iana>.
