### ISSUE TITLE
Registration Request: mercure

### ISSUE THREAD

**Issue by dunglas** [protocol-registries/link-relations#21]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8288#section-2.1.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/link-relations/) and found no current link relation types that meet your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

Enter the details of the link relation type below:

* Relation Name: mercure
* Description: The Mercure Hub to use to subscribe to updates of this resource.
* Reference: https://datatracker.ietf.org/doc/draft-dunglas-mercure/

Any additional information (this will not be included in the registry)?

The Mercure is already widely used (see the Implementation Status section of the I-D) and is already listed in the [List of /.well-known/ services offered by webservers](https://en.wikipedia.org/wiki/List_of_/.well-known/_services_offered_by_webservers) Wikipedia page.
I plan to propose this I-D as a RFC soon.

The registration of well-known URI has also be started: https://github.com/protocol-registries/well-known-uris/issues/4

**Comment by mnot** [comment]
Hello,

The specification document you list is an Internet-Draft that isn't currently on any stream (IETF, IAB, Independent or IRTF), and as such isn't a suitable reference for registration. Once it's on a stream, it can be considered for provisional registration, becoming permanent when it's an RFC.

Thank you,

**Comment by mnot** [comment]
Draft is long expired; closing.
