### ISSUE TITLE
Request to register "linkset" link relation type

### ISSUE THREAD

**Issue by hvdsomp** [protocol-registries/link-relations#23]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8288#section-2.1.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/link-relations/) and found no current link relation types that meet your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

Enter the details of the link relation type below:

* Relation Name: linkset
* Description: The Target IRI of a link with the "linkset" relation type provides a set of links, including links in which the Context IRI of the link participates.
* Reference: https://datatracker.ietf.org/doc/draft-wilde-linkset/

Any additional information (this will not be included in the registry)? We are requesting registration of the "linkset" link relation type on the basis of the I-D (not yet RFC) because implementations exist (e.g. OJS - see the I-D), are ongoing (e.g. GS1 - see the I-D and [https://github.com/dret/I-D/issues/139#issuecomment-709883242](https://github.com/dret/I-D/issues/139#issuecomment-709883242)), and others can be expected as a result of the publication of the [FAIR Signposting Profile](https://signposting.org/FAIR/). The plan is to wrap up work on the I-D and move to publication as an RFC asap.

**Comment by mnot** [comment]
Holding this until the I-D is adopted on a stream.

**Comment by hvdsomp** [comment]
The I-D was on the agenda of the recent/first meeting of the IETF HTTP API WG. Does this qualify for the “adopted on a stream” criterium, in which case “linkset” could be added to the Link Relation Type registry now?

**Comment by mnot** [comment]
Hi Herbert,

I see that there's a Call for Adoption out now. Assuming that it's adopted, we usually register when things are a bit more advanced (around WGLC, or even later), to make sure that there aren't any changes along the way. Consider it reserved here; I'll leave this issue open as a reminder.

**Comment by hvdsomp** [comment]
OK, thanks, @mnot!

**Comment by mnot** [comment]
OBE; linkset was adopted by HTTPAPI and IANA added the value as part of their processing.
