### ISSUE TITLE
Authentication-related link relations

### ISSUE THREAD

**Issue by evert** [protocol-registries/link-relations#24]
Please confirm that:

* [X] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8288#section-2.1.1).
* [X] You have checked [the registry](https://www.iana.org/assignments/link-relations/) and found no current link relation types that meet your needs.
* [ ] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the link relation type below:

### authenticate

* Relation Name: authenticate
* Description: The "authenticate" can be used to link to a resource that hosts a
   page where a user can authenticate itself for the current resource.
* Reference: https://tools.ietf.org/html/draft-pot-authentication-link-01#section-2

### authenticated-as

* Relation Name: authenticated-as
* Description: The "authenticated-as" link refers to a resource that describes the
   effective authenticated user for a HTTP response.
* Reference: https://tools.ietf.org/html/draft-pot-authentication-link-01#section-3

### logout

* Relation Name: logout
* Description: The "logout" link refers to a resource where an authenticated user might
   end their session.
* Reference: https://tools.ietf.org/html/draft-pot-authentication-link-01#section-4

### register-user

* Relation Name: register-user
* Description: The "register-user" Link Relation refers to a resource where a user
   might sign up for a service for the context URI.
* Reference: https://tools.ietf.org/html/draft-pot-authentication-link-01#section-5

Any additional information (this will not be included in the registry)?

**Comment by mnot** [comment]
Hi evert,

We generally don't register relations in Internet-Drafts until they're adopted by a WG, and often not until they're almost published. An unadopted I-D is not considered a stable reference.

I'll leave this open to soft-reserve them in case they do progress.

Cheers,

**Comment by mnot** [comment]
Closing; the draft has long expired.
