### ISSUE TITLE
Request to register application-figure

### ISSUE THREAD

**Issue by sbp** [protocol-registries/link-relations#27]
Please confirm that:

* [Y] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8288#section-2.1.1).
* [Y] You have checked [the registry](https://www.iana.org/assignments/link-relations/) and found no current link relation types that meet your needs.
* [Y] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the link relation type below:

* Relation Name: application-figure
* Description: Refers to a resource with an available representation in the 'application' media type subtree suitable for rendering within the context.
* Reference: https://purl.org/net/figure-link-rels

Any additional information (this will not be included in the registry)?

It's not clear whether RFC 8288's injunction that link relations "MUST NOT constrain the available representation media types of the link target" refers to constraining to specific individual media types, or placing any restriction on media types. The figure-link-rels specification says that a resource has **a** representation in a specific subtree, but does not restrict *other* representations, nor does it restrict to any specific media types.

**Comment by mnot** [comment]
It's still a constraint. What's the use case that you have for separating these relations out? note that target attributes often carry type information; e.g.,

> Link: </foo>; rel="figure"; type="application/whatever"

**Comment by sbp** [comment]
Yeah, but the subtype can't be a wildcard so you can't do this:

```
Link: ; rel="figure"; type="application/*"
```

And some environments may lack a type hint altogether. Therefore the use case is effectively providing subtype-wildcarded media type information inside the relation itself.

Could you explain the motivation for forbidding any form of media type constraint in link relations?

At the moment, the figure-link-rels specification says that the typed rels guarantee at least one representation in the supertype. If I changed that so that it were to become *only a hint*, much like the type attribute in the Link header or the type attribute in HTML, would that be enough to steer clear of RFC 8288's injunction?

**Comment by mnot** [comment]
Can you illustrate a case where it would make sense to mint a link pointing at a document with a wildcard type?

The requirement is there to prevent link relations to be used in a way that duplicates media types -- which is what you appear to be trying to do.

**Comment by mnot** [comment]
Closing as stale.
