### ISSUE TITLE
Request to register "acl" link relation type

### ISSUE THREAD

**Issue by csarven** [protocol-registries/link-relations#32]
Please confirm that:

* [X] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8288#section-2.1.1).
* [X] You have checked [the registry](https://www.iana.org/assignments/link-relations/) and found no current link relation types that meet your needs.
* [X] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the link relation type below:

* Relation Name: acl
* Description: The relationship A acl B asserts that resource B provides access control description of resource A. There are no constraints on the format or representation of either A or B, neither are there any further constraints on either resource.
* Reference: https://solidproject.org/TR/wac

Any additional information (this will not be included in the registry)? The [W3C Solid Community Group](https://www.w3.org/community/solid/) is requesting registration of the "acl" link relation type on the basis of the Web Access Control (WAC) specification, as well as other specifications using the link relation. Implementations exist, are ongoing, and others can be expected as a result of the publication. The plan is to wrap up work on the draft and move to "final" publication. The specification reference URL is managed by the Solid Project and the versioned URLs are covered by the URI Persistence Policy: https://solidproject.org/terms#uri-persistence-policy .

**Comment by timbl** [comment]
The rel=acl link has been used for a long time, too.

**Comment by mnot** [comment]
Sorry for the delay. This is fine, with a couple of tweaks:

* The description should use terminology from the RFC; i.e., 'link target' and 'link context'.

* Drop the last sentence of the description, as that's implied for all link relations unless stated otherwise (and I actually might request that IANA state so at the top of the registry).

* The reference URL should be to the pinpoint of the registration

That leads us to: 

• Relation Name: acl
• Description: Asserts that the link target provides an access control description for the link context. 
• Reference: https://solidproject.org/TR/wac#acl-link-relation

If that works for you, I'll request registration at IANA.

Cheers,

**Comment by csarven** [comment]
Great, thank you. I've updated the Editor's Draft (ED) as per your recommendation: https://solid.github.io/web-access-control-spec/#acl-link-relation . We'll update TR/wac once the ED snapshot is approved for publication. Do you need that in before continuing with the process?

Some of the text in the #acl-link-relation section may change, e.g., once the relation type is in the registry, mention of IANA review/approval will be removed. And, we may even remove the advisements at the bottom altogether at a later date. Is there anything within the description of #acl-link-relation that MUST NOT change besides three fields (Relation Name, Description, Reference)?

Is there any documentation/recommendation on using or ensuring that the Reference is an immutable resource or anything along the lines of a snapshot from a third-party like the Internet Archive?

**Comment by mnot** [comment]
The URI you've given is sufficient -- we generally try to avoid personal project URLs and the like. If it changes, just open a modification request. Thanks!

**Comment by timbl** [comment]
I'd prefer " Description: Asserts that the link target provides an access control resource for the link context." as 'description' suggests extra optional data while the ACR is a crucial bit of the system.  A non-existent one has semantics. An empty one has different semantics. And so on.

**Comment by mnot** [comment]
That works too -- @csarven?

**Comment by csarven** [comment]
@mnot , yes that works. We've actually updated the editor's draft as per @timbl 's suggestion and was in the process of publishing it at the reference URL (see backlinked PR referring to this issue.)

Should this issue be reopened? :) is there anything else we need to do on our end besides publishing the updated definition in the spec?

**Comment by mnot** [comment]
Tell me when it's stable (e.g., you merge) and I'll update the registry.

Cheers,

**Comment by csarven** [comment]
Thanks for your patience.

https://solidproject.org/TR/wac#acl-link-relation is accessible now.
