### ISSUE TITLE
base

### ISSUE THREAD

**Issue by petersilva** [protocol-registries/link-relations#34]
Please confirm that:

* [x ] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8288#section-2.1.1).
* [x ] You have checked [the registry](https://www.iana.org/assignments/link-relations/) and found no current link relation types that meet your needs.
* [ x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the link relation type below:

* Relation Name: base
* Description: provide a base url for use by other links.
* Reference: https://html.spec.whatwg.org/#the-base-element

Any additional information (this will not be included in the registry)?

For my use case, I would like have links of the form:

rel=base  href="https://example.com/origin/of/api"
rel=item href="arguments/to/API"

or it could be a static file case:

rel=base href="https://example.com/a/b"
rel=item href="c/d.txt"

in the case of collections, there could be some reduction in bytes used by avoiding the need to repeat the base URL in each item.  I chose item for the example, but many other relations could make use of a relative url scheme.
This is useful when link relations are not embedded in html, but in a JSON payload (my use case.) where the
html base element is not available.

**Comment by mnot** [comment]
`base` isn't specified as a link relation by HTML, as far as I can see. You should first engage with them to get this change in their spec.

**Comment by petersilva** [comment]
HTML doesn't need a "base" link relation, because they have the base element present (see linked standard reference), which can be used by all link types. in other words, all links elements can contain relative HREFs, which are already defined by the standard to be expected to use the BASE element. There will never be a "base" relation in the link element for HTML for that reason.

**Comment by reschke** [comment]
AFAICT, this would be a breaking change, as it would change the interpretation of other links in a message.

**Comment by dret** [comment]
On 2022-04-27 23:03, Peter Silva wrote:
>   * Relation Name: base
>   * Description: provide a base url for use by other links.
>   * Reference: https://html.spec.whatwg.org/#the-base-element

this looks like it would potentially break many things in many places, 
because supporting it or not would change the interpretation of other 
(unrelated) protocol elements.

> rel="base" href="https://example.com/origin/of/api 
> rel="item" href="arguments/to/API"

this is a good example for the potential problem. an implementation 
supporting "base" would interpret the "item" link differently than an 
implementation not supporting "base". this kind of dependency is a 
well-known anti-pattern in terms of openness and extensibility.

-- 
erik wilde | ***@***.*** |
            | http://twitter.com/dret    |

**Comment by petersilva** [comment]
Today, if link are within a web page, the HTML base element must already be honoured, so doesn't anyone interpreting links already have to deal with all those cases? Today, we have the case where all those cases must be honoured when embedded in a web page, but the same relations cannot be expressed when not in a web page because of this missing element.  

Do you have a link to describe the anti-pattern you have in mind?

**Comment by reschke** [comment]
> Today, if link are within a web page, the HTML base element must already be honoured, so doesn't anyone interpreting links already have to deal with all those cases? Today, we have the case where all those cases must be honoured when embedded in a web page, but the same relations cannot be expressed when not in a web page because of this missing element.

Anybody interpreting link relations already has to deal with relative links; yes. But the proposal changes the link context, so recipients implementing the new link relation will use a different base URI than those who do not. This is a breaking change.

**Comment by dret** [comment]
On 2022-04-28 14:07, Peter Silva wrote:
> Today, if link are within a web page, the HTML base element must already 
> be honoured, so doesn't anyone interpreting links already have to deal 
> with all those cases? Today, we have the case where all those cases must 
> be honoured when embedded in a web page, but the same relations cannot 
> be expressed when not in a web page because of this missing element.

typed links (i.e., links using link relations) are used in many more 
places than just in HTML. there are many applications out there (many 
more than the relatively few browsers) that use typed links, for example 
for processing messages in APIs. all of these would break with the 
proposed link relation.

**Comment by petersilva** [comment]
How do relative links work in the proposed cases of breakage? my understanding is a relative link outside an HTML page is currently undefined,  How would someone know what the base URL of a link is in an API?  I've had several smart people tell me: "Don't use relative uri's..."  or that relative urls are not "of the web"... which seems to be common practice/belief, in which case the breakage would be nil, as it would only affect those who actually use relative paths in url's outside HTML.

My use case is actually trying to use link relations in an API payload, and I can't figure out how to specify a base... and using absolute ones in every link seems painful. Plus in my application, I need to extract the base URL, and there isn't a reliable way to do that, so it would be easier if I could specify a base rel.

**Comment by petersilva** [comment]
@reschke Thank You!  I think what you are saying is that rather than having a relation, one can use the link context to specify an anchor url to provide the same benefit as a base relation.  But reading the standard, I don't see how to specify an anchor.  Can you provide an example of how it would be used?

**Comment by reschke** [comment]
It's defined for links in HTML and in HTTP messages. If you take the link somewhere else, you'll have to define the mechanism for that type of context.

**Comment by petersilva** [comment]
ah... ok back to square one... We don't need this relation for the html case because it has several methods for providing context for relative links, but outside HTML, it seems to be undefined.

**Comment by reschke** [comment]
Hm no. It's defined for Link header fields as well, and will also be defined for the formats defined in draft-ietf-httpapi-linkset.

**Comment by petersilva** [comment]
ok I misunderstood... trying to understand how to apply the standard.
Is this: https://www.ietf.org/archive/id/draft-ietf-httpapi-linkset-04.html#section-4.2 what you are referring to?
So looking at the examples there, and there are no relative links, in spite of the presence of an anchor.  I understand the anchor as a sort of parent object pointer, but I'm not sure if it is meant to be user as a base URL for objects within the linkset.  So I'm not sure if it's the right idea or not.  any other examples?
