### ISSUE TITLE
`reg-rel-type` rule and registered Link Relations

### ISSUE THREAD

**Issue by csarven** [protocol-registries/link-relations#44]
https://datatracker.ietf.org/doc/html/rfc8288#section-2.1.1 states the following:

>Registered relation type names MUST conform to the reg-rel-type rule
   (see [Section 3.3](https://datatracker.ietf.org/doc/html/rfc8288#section-3.3)) and MUST be compared character by character in a
   case-insensitive fashion.

and https://datatracker.ietf.org/doc/html/rfc8288#section-3.3 includes the following definition for `reg-rel-type`:

>`reg-rel-type   = LOALPHA *( LOALPHA / DIGIT / "." / "-" )`

There are registered Link Relation types in https://www.iana.org/assignments/link-relations/link-relations that do not appear to conform to `reg-rel-type`, i.e., they use `ALPHA`.

If the definition of `reg-rel-type` is correct, then there are registered types do not conform.

If the definition of `reg-rel-type` is incorrect, then the definition should be updated to use `ALPHA` instead of  `LOALPHA`.

---

I was just about to report an errata about the definition of `LOALPHA` not being carried forward in later HTTP and ABNF specs, as well as not defined in RFC 8288, but have noticed that it was already "Reported" (but not yet "Verified") at https://www.rfc-editor.org/errata/eid5319 .

While accepting errata/eid5319 will correct RFC 8288, `reg-rel-type` may still need to be updated to use `ALPHA` to ensure that existing and future registrations conform to the spec. I can submit an errata if that makes sense.

**Comment by mnot** [comment]
Thanks for noticing this. Given that link relation types are compared in a case-insensitive fashion, the best path forward is to correct the registry, which IANA has done.
